language: python
python:
  - 3.6
before_install:
  - sudo apt-get install software-properties-common
install:
  - pip install coverage
  - python setup.py develop
script:
  - ls
  - python -m unittest discover -s ./tests
notifications:
  webhooks:
    - https://lamden-discord-travisci.herokuapp.com/webhook/
