version: 2
jobs:
  build:
    working_directory: ~/cilantro
    docker:
      - image: circleci/python:3.6.5
      - image: lamden/cilantro-db
        environment:
          username: cilantro_user
          password: buttcoins
          database: cilantro_dev
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: cilantro-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Cilantro Requirements
          command: |
             pip install -r requirements.txt --upgrade --no-cache-dir --exists-action w
             make update-submodules

      - run:
          name: Install Mysql Client
          command: |
             sudo apt install -y mysql-client

#      # This should go into custom primary image, here's only for the sake of explanation
#      - run:
#          name: Install Docker client
#          command: |
#            set -x
#            VER="17.03.0-ce"
#            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
#            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
#            mv /tmp/docker/* /usr/bin
#      # This should go into custom primary image, here's only for the sake of explanation
#      - run:
#          name: Install Docker Compose
#          command: |
#            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
#            chmod +x ~/docker-compose
#            sudo mv ~/docker-compose /usr/local/bin/docker-compose
#
#      - setup_remote_docker

      - run:
          name: set temp credentials file (aka db config stuff)
          command: |
             ./scripts/make_test_config.py --password buttcoins --username cilantro_user --database cilantro_dev --hostname 127.0.0.1

      - save_cache:
          key: cilantro-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"

      - run:
          name: Wait For mysqld
          command: |
            dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Run Tests
          command: |
            export PYTHONPATH=$PYTHONPATH:~/cilantro
            export LOCAL_PATH=~
            python3.6 ~/cilantro/tests/run_tests.py --integration 0

      - store_artifacts:
          path: test-results
          destination: tr1
