version: 2
jobs:
  build:
    working_directory: ~/cilantro
    docker:
      - image: circleci/python:3.6.5
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: cilantro-{{ .Branch }}-{{ checksum "reqiurements.txt" }}
      - run:
          name: Install Cilantro Requirements
          command: |
            sudo pip install pipenv
            pipenv install


#      # This should go into custom primary image, here's only for the sake of explanation
#      - run:
#          name: Install Docker client
#          command: |
#            set -x
#            VER="17.03.0-ce"
#            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
#            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
#            mv /tmp/docker/* /usr/bin
#      # This should go into custom primary image, here's only for the sake of explanation
#      - run:
#          name: Install Docker Compose
#          command: |
#            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
#            chmod +x ~/docker-compose
#            sudo mv ~/docker-compose /usr/local/bin/docker-compose
#
#      - setup_remote_docker

      - save_cache:
          key: cilantro-{{ .Branch }}-{{ checksum "reqiurements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"

      - run:
          command: |
            export PYTHONPATH=$PYTHONPATH:~/cilantro
            export LOCAL_PATH=~
            pipenv run python ~/cilantro/tests/run_tests.py --integration 0
      - store_artifacts:
          path: test-results
          destination: tr1
